// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using OptraxDAL;

#nullable disable

namespace OptraxDAL.Migrations
{
    [DbContext(typeof(OptraxContext))]
    [Migration("20250318074646_UpdateIcons2")]
    partial class UpdateIcons2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IconCollectionMapIcon", b =>
                {
                    b.Property<int>("CollectionsID")
                        .HasColumnType("int");

                    b.Property<int>("IconsID")
                        .HasColumnType("int");

                    b.HasKey("CollectionsID", "IconsID");

                    b.HasIndex("IconsID");

                    b.ToTable("IconCollectionMapIcon", "Map");
                });

            modelBuilder.Entity("LocationStockItem", b =>
                {
                    b.Property<int>("LocationsID")
                        .HasColumnType("int");

                    b.Property<int>("StockItemsID")
                        .HasColumnType("int");

                    b.HasKey("LocationsID", "StockItemsID");

                    b.HasIndex("StockItemsID");

                    b.ToTable("LocationStockItem");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "Identity");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Address2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("BuildingID")
                        .HasColumnType("int");

                    b.Property<int?>("BusinessID")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreatedByID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedByID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.HasIndex("BusinessID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", "Identity");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.Business", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedByID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LastModifiedByID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.Input", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CreatedByID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InputName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastModifiedByID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("InputName")
                        .IsUnique();

                    b.ToTable("Inputs");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CreatedByID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LastModifiedByID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("MapObjectID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MapObjectID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentID");

                    b.ToTable("Locations");

                    b.HasDiscriminator<string>("LocationType").HasValue("Location");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.UoM", b =>
                {
                    b.Property<string>("UnitName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedByID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastModifiedByID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PerQuantity")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("UnitAbbr")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("UnitName");

                    b.ToTable("UoMs");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Batch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedByID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CropID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedByID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OriginType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PropagationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CropID");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Crop", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BatchID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedByID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentPhase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ExpectedFlowerDays")
                        .HasColumnType("int");

                    b.Property<int?>("ExpectedVegDays")
                        .HasColumnType("int");

                    b.Property<int?>("FieldLocationID")
                        .HasColumnType("int");

                    b.Property<int?>("GreenhouseLocationID")
                        .HasColumnType("int");

                    b.Property<string>("LastModifiedByID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomLocationID")
                        .HasColumnType("int");

                    b.Property<int?>("RowLocationID")
                        .HasColumnType("int");

                    b.Property<int?>("SpeciesID")
                        .HasColumnType("int");

                    b.Property<int>("StrainID")
                        .HasColumnType("int");

                    b.Property<decimal?>("WasteQuantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("WasteQuantityUoM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BatchID")
                        .IsUnique()
                        .HasFilter("[BatchID] IS NOT NULL");

                    b.HasIndex("FieldLocationID");

                    b.HasIndex("GreenhouseLocationID");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.HasIndex("RoomLocationID");

                    b.HasIndex("RowLocationID");

                    b.HasIndex("SpeciesID");

                    b.HasIndex("StrainID");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Cultivar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CreatedByID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedByID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Patented")
                        .HasColumnType("bit");

                    b.Property<int>("SpeciesID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SpeciesID");

                    b.ToTable("Cultivars");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.PlantEvent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ContainerTypeID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventSubType")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("LightID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("PlantID")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ContainerTypeID");

                    b.HasIndex("LightID");

                    b.HasIndex("PlantID");

                    b.HasIndex("UserID");

                    b.ToTable("PlantEvents");

                    b.HasDiscriminator<string>("EventType").HasValue("PlantEvent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Species", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Abbreviation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Attracts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvoidPlants")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BestPlantingMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloomPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloomShape")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloomSizeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Branching")
                        .HasColumnType("bit");

                    b.Property<bool?>("ColdStratify")
                        .HasColumnType("bit");

                    b.Property<string>("ColdStratifyDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommonDiseases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommonPests")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanionPlants")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CropRotationDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DaysToMaturity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrainageNeeds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FloralCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GerminationDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GerminationTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HardenOff")
                        .HasColumnType("bit");

                    b.Property<string>("HardenOffDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HardinessZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HarvestDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HarvestPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HarvestSignifiers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeatZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdealDayTemp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdealHumidity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdealLightHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdealNightTemp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdealSoilTemp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdealpH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsInvasive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedByID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeafCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainPropagationMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxStorageDays")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pinch")
                        .HasColumnType("bit");

                    b.Property<string>("PlantHeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantSpacing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropagationTypes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Repels")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resistances")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskFactors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RowSpacing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seasons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeedDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeedLifespan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeedOrBulbDepth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeedStorageDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoilType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Spread")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StemLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaseLife")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaterNeedsFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WaterNeedsQty")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("ID");

                    b.HasIndex("SpeciesName")
                        .IsUnique();

                    b.ToTable("Species");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Strain", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedByID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("Generation")
                        .HasColumnType("int");

                    b.Property<string>("LastModifiedByID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OriginID")
                        .HasColumnType("int");

                    b.Property<string>("OriginType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StrainType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Strains");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.StrainRelationship", b =>
                {
                    b.Property<int>("ParentID")
                        .HasColumnType("int");

                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.HasKey("ParentID", "ChildID");

                    b.HasIndex("ChildID");

                    b.ToTable("StrainRelationships");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Variety", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CreatedByID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedByID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Varieties");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.ContainerType", b =>
                {
                    b.Property<int>("ContainerTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContainerTypeID"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Capacity")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("CreatedByID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastModifiedByID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UoMName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ContainerTypeID");

                    b.HasIndex("UoMName");

                    b.ToTable("ContainerTypes");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.InventoryCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedByID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HexColor")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastModifiedByID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<string>("TextColor")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentID");

                    b.ToTable("InventoryCategories");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.InventoryItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DefaultUoM")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LastModifiedByID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("NeedsTransferApproval")
                        .HasColumnType("bit");

                    b.Property<string>("SKU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SellerID")
                        .HasColumnType("int");

                    b.Property<string>("StockType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StockUoM")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Tags")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SKU")
                        .IsUnique()
                        .HasFilter("[SKU] IS NOT NULL");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.InventoryTransfer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ApprovalID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DestinationID")
                        .HasColumnType("int");

                    b.Property<bool>("IsPartial")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedsApproval")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StockItemID")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCount")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("UnitUoM")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("DestinationID");

                    b.HasIndex("OriginID");

                    b.HasIndex("StockItemID");

                    b.HasIndex("UserID");

                    b.ToTable("InventoryTransfers");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.StockItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CreatedByID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExpirationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("InventoryItemID")
                        .HasColumnType("int");

                    b.Property<string>("LastModifiedByID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("NeedsTransferApproval")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("PurchaseDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("PurchasePrice")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("InventoryItemID");

                    b.ToTable("StockItems");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.TransferApproval", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTimeOffset>("ApprovalDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ManagerID")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransferID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ManagerID");

                    b.HasIndex("TransferID")
                        .IsUnique();

                    b.ToTable("TransferApprovals");
                });

            modelBuilder.Entity("OptraxDAL.Models.Map.IconCollection", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.ToTable("IconCollections", "Map");
                });

            modelBuilder.Entity("OptraxDAL.Models.Map.MapIcon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Icons", "Map");
                });

            modelBuilder.Entity("OptraxDAL.Models.Map.MapObject", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedByID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedByID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.ToTable("MapObjects", "Map");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("OptraxDAL.Models.Products.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedByID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedByID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UnitUoMName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("ProductName")
                        .IsUnique();

                    b.HasIndex("UnitUoMName");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OptraxDAL.Models.Products.ProductBatch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BatchNumber")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedByID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("UnitQuantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductBatches");
                });

            modelBuilder.Entity("OptraxDAL.Models.Products.ProductItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BatchID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CropID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DateLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedByID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasFilter("[Barcode] IS NOT NULL");

                    b.HasIndex("BatchID");

                    b.HasIndex("CropID");

                    b.HasIndex("LocationID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductItems");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.BedLocation", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Admin.Location");

                    b.ToTable("Locations");

                    b.HasDiscriminator().HasValue("Bed");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.BuildingLocation", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Admin.Location");

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<int>("BusinessID")
                        .HasColumnType("int");

                    b.HasIndex("AddressID")
                        .IsUnique()
                        .HasFilter("[AddressID] IS NOT NULL");

                    b.HasIndex("BusinessID");

                    b.ToTable("Locations");

                    b.HasDiscriminator().HasValue("Building");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.FieldLocation", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Admin.Location");

                    b.ToTable("Locations");

                    b.HasDiscriminator().HasValue("Field");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.GreenhouseLocation", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Admin.Location");

                    b.ToTable("Locations");

                    b.HasDiscriminator().HasValue("Greenhouse");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.OffsiteLocation", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Admin.Location");

                    b.Property<int?>("AddressID")
                        .HasColumnType("int");

                    b.Property<int?>("BusinessID")
                        .HasColumnType("int");

                    b.HasIndex("AddressID");

                    b.HasIndex("BusinessID");

                    b.ToTable("Locations", t =>
                        {
                            t.Property("AddressID")
                                .HasColumnName("OffsiteLocation_AddressID");

                            t.Property("BusinessID")
                                .HasColumnName("OffsiteLocation_BusinessID");
                        });

                    b.HasDiscriminator().HasValue("Offsite");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.PlotLocation", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Admin.Location");

                    b.ToTable("Locations");

                    b.HasDiscriminator().HasValue("Plot");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.RoomLocation", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Admin.Location");

                    b.ToTable("Locations");

                    b.HasDiscriminator().HasValue("Room");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.RowLocation", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Admin.Location");

                    b.ToTable("Locations");

                    b.HasDiscriminator().HasValue("Row");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.SiteLocation", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Admin.Location");

                    b.Property<int?>("BusinessID")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.HasIndex("BusinessID");

                    b.ToTable("Locations", t =>
                        {
                            t.Property("BusinessID")
                                .HasColumnName("SiteLocation_BusinessID");
                        });

                    b.HasDiscriminator().HasValue("Site");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.VehicleLocation", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Admin.Location");

                    b.ToTable("Locations");

                    b.HasDiscriminator().HasValue("Vehicle");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.GrowthEvent", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Grow.PlantEvent");

                    b.Property<string>("NewPhase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("PlantEvents");

                    b.HasDiscriminator().HasValue("Growth");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.PruneEvent", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Grow.PlantEvent");

                    b.Property<string>("PruneType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WasteQuantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("WasteQuantityUOM")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("PlantEvents");

                    b.HasDiscriminator().HasValue("Prune");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.TransferEvent", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Grow.PlantEvent");

                    b.Property<int>("TransferID")
                        .HasColumnType("int");

                    b.HasIndex("TransferID")
                        .IsUnique()
                        .HasFilter("[TransferID] IS NOT NULL");

                    b.ToTable("PlantEvents");

                    b.HasDiscriminator().HasValue("Transfer");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.TransplantEvent", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Grow.PlantEvent");

                    b.Property<int>("NewContainerID")
                        .HasColumnType("int");

                    b.HasIndex("NewContainerID");

                    b.ToTable("PlantEvents");

                    b.HasDiscriminator().HasValue("Transplant");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.TreatmentEvent", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Grow.PlantEvent");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<decimal?>("QuantityApplied")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("QuantityUoM")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TreatmentType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasIndex("ProductID");

                    b.ToTable("PlantEvents");

                    b.HasDiscriminator().HasValue("Treatment");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.ConsumableItem", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Inventory.StockItem");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitCount")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("UoMName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasIndex("UoMName");

                    b.ToTable("Consumables", (string)null);
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.DurableItem", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Inventory.StockItem");

                    b.Property<DateTimeOffset?>("LastMaintenanceCheck")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MaintenanceInterval")
                        .HasColumnType("int");

                    b.Property<string>("MaintenanceInvervalUoM")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.ToTable("DurableItems", (string)null);
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.Light", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Inventory.StockItem");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("FirstInstallDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastMaintenanceCheck")
                        .HasColumnType("datetimeoffset");

                    b.ToTable("Lights", (string)null);
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.Plant", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Inventory.StockItem");

                    b.Property<int?>("CropID")
                        .HasColumnType("int");

                    b.Property<int?>("CultivarID")
                        .HasColumnType("int");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PropagationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesID")
                        .HasColumnType("int");

                    b.Property<int?>("StrainID")
                        .HasColumnType("int");

                    b.Property<string>("TrackingID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VarietyID")
                        .HasColumnType("int");

                    b.HasIndex("CropID");

                    b.HasIndex("ParentID");

                    b.HasIndex("StrainID");

                    b.ToTable("Plants", (string)null);
                });

            modelBuilder.Entity("OptraxDAL.Models.Map.MapLine", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Map.MapObject");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<LineString>("LineGeometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.ToTable("Lines", "Map");
                });

            modelBuilder.Entity("OptraxDAL.Models.Map.MapPoint", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Map.MapObject");

                    b.Property<int>("IconID")
                        .HasColumnType("int");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(12, 8)
                        .HasColumnType("decimal(12,8)");

                    b.Property<int?>("LocationID")
                        .HasColumnType("int");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(12, 8)
                        .HasColumnType("decimal(12,8)");

                    b.Property<int?>("MapLineID")
                        .HasColumnType("int");

                    b.Property<int?>("MapPolygonID")
                        .HasColumnType("int");

                    b.HasIndex("IconID");

                    b.HasIndex("LocationID");

                    b.HasIndex("MapLineID");

                    b.HasIndex("MapPolygonID");

                    b.ToTable("Points", "Map");
                });

            modelBuilder.Entity("OptraxDAL.Models.Map.MapPolygon", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Map.MapObject");

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BorderWidth")
                        .HasColumnType("int");

                    b.Property<string>("FillColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Polygon>("PolyGeometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.HasIndex("LocationID");

                    b.ToTable("Polygons", "Map");
                });

            modelBuilder.Entity("IconCollectionMapIcon", b =>
                {
                    b.HasOne("OptraxDAL.Models.Map.IconCollection", null)
                        .WithMany()
                        .HasForeignKey("CollectionsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Map.MapIcon", null)
                        .WithMany()
                        .HasForeignKey("IconsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LocationStockItem", b =>
                {
                    b.HasOne("OptraxDAL.Models.Admin.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Inventory.StockItem", null)
                        .WithMany()
                        .HasForeignKey("StockItemsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OptraxDAL.Models.Admin.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OptraxDAL.Models.Admin.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Admin.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OptraxDAL.Models.Admin.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.Address", b =>
                {
                    b.HasOne("OptraxDAL.Models.Admin.Business", "Business")
                        .WithMany("Addresses")
                        .HasForeignKey("BusinessID");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.Location", b =>
                {
                    b.HasOne("OptraxDAL.Models.Map.MapObject", "MapObject")
                        .WithMany()
                        .HasForeignKey("MapObjectID");

                    b.HasOne("OptraxDAL.Models.Admin.Location", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentID");

                    b.Navigation("MapObject");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Batch", b =>
                {
                    b.HasOne("OptraxDAL.Models.Grow.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Crop", b =>
                {
                    b.HasOne("OptraxDAL.Models.Admin.FieldLocation", null)
                        .WithMany("Crops")
                        .HasForeignKey("FieldLocationID");

                    b.HasOne("OptraxDAL.Models.Admin.GreenhouseLocation", null)
                        .WithMany("Crops")
                        .HasForeignKey("GreenhouseLocationID");

                    b.HasOne("OptraxDAL.Models.Admin.RoomLocation", null)
                        .WithMany("Crops")
                        .HasForeignKey("RoomLocationID");

                    b.HasOne("OptraxDAL.Models.Admin.RowLocation", null)
                        .WithMany("Crops")
                        .HasForeignKey("RowLocationID");

                    b.HasOne("OptraxDAL.Models.Grow.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesID");

                    b.HasOne("OptraxDAL.Models.Grow.Strain", null)
                        .WithMany("Crops")
                        .HasForeignKey("StrainID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Cultivar", b =>
                {
                    b.HasOne("OptraxDAL.Models.Grow.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.PlantEvent", b =>
                {
                    b.HasOne("OptraxDAL.Models.Inventory.ContainerType", null)
                        .WithMany("Transplants")
                        .HasForeignKey("ContainerTypeID");

                    b.HasOne("OptraxDAL.Models.Inventory.Light", null)
                        .WithMany("PlantLightEvents")
                        .HasForeignKey("LightID");

                    b.HasOne("OptraxDAL.Models.Inventory.Plant", "Plant")
                        .WithMany("PlantEvents")
                        .HasForeignKey("PlantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Admin.AppUser", "User")
                        .WithMany("PlantEvents")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.StrainRelationship", b =>
                {
                    b.HasOne("OptraxDAL.Models.Grow.Strain", "ChildStrain")
                        .WithMany("Parents")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Grow.Strain", "ParentStrain")
                        .WithMany("Children")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildStrain");

                    b.Navigation("ParentStrain");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.ContainerType", b =>
                {
                    b.HasOne("OptraxDAL.Models.Admin.UoM", "CapacityUoM")
                        .WithMany()
                        .HasForeignKey("UoMName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CapacityUoM");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.InventoryCategory", b =>
                {
                    b.HasOne("OptraxDAL.Models.Inventory.InventoryCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentID");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.InventoryItem", b =>
                {
                    b.HasOne("OptraxDAL.Models.Inventory.InventoryCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.InventoryTransfer", b =>
                {
                    b.HasOne("OptraxDAL.Models.Admin.Location", "Destination")
                        .WithMany("TransfersIn")
                        .HasForeignKey("DestinationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Admin.Location", "Origin")
                        .WithMany("TransfersOut")
                        .HasForeignKey("OriginID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Inventory.StockItem", "StockItem")
                        .WithMany("Transfers")
                        .HasForeignKey("StockItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Admin.AppUser", "User")
                        .WithMany("InventoryTransfers")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Origin");

                    b.Navigation("StockItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.StockItem", b =>
                {
                    b.HasOne("OptraxDAL.Models.Inventory.InventoryItem", "InventoryItem")
                        .WithMany("StockItems")
                        .HasForeignKey("InventoryItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.TransferApproval", b =>
                {
                    b.HasOne("OptraxDAL.Models.Admin.AppUser", "Manager")
                        .WithMany("TransferApprovals")
                        .HasForeignKey("ManagerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Inventory.InventoryTransfer", "Transfer")
                        .WithOne("Approval")
                        .HasForeignKey("OptraxDAL.Models.Inventory.TransferApproval", "TransferID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("OptraxDAL.Models.Map.IconCollection", b =>
                {
                    b.HasOne("OptraxDAL.Models.Map.IconCollection", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentID");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("OptraxDAL.Models.Products.Product", b =>
                {
                    b.HasOne("OptraxDAL.Models.Admin.UoM", "UnitUoM")
                        .WithMany()
                        .HasForeignKey("UnitUoMName");

                    b.Navigation("UnitUoM");
                });

            modelBuilder.Entity("OptraxDAL.Models.Products.ProductBatch", b =>
                {
                    b.HasOne("OptraxDAL.Models.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OptraxDAL.Models.Products.ProductItem", b =>
                {
                    b.HasOne("OptraxDAL.Models.Products.ProductBatch", "Batch")
                        .WithMany("Units")
                        .HasForeignKey("BatchID");

                    b.HasOne("OptraxDAL.Models.Grow.Crop", null)
                        .WithMany("ProductItems")
                        .HasForeignKey("CropID");

                    b.HasOne("OptraxDAL.Models.Admin.Location", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("LocationID");

                    b.HasOne("OptraxDAL.Models.Products.Product", "Product")
                        .WithMany("Units")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("CurrentLocation");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.BuildingLocation", b =>
                {
                    b.HasOne("OptraxDAL.Models.Admin.Address", "Address")
                        .WithOne("Building")
                        .HasForeignKey("OptraxDAL.Models.Admin.BuildingLocation", "AddressID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Admin.Business", "Business")
                        .WithMany("Buildings")
                        .HasForeignKey("BusinessID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.OffsiteLocation", b =>
                {
                    b.HasOne("OptraxDAL.Models.Admin.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID");

                    b.HasOne("OptraxDAL.Models.Admin.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessID");

                    b.Navigation("Address");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.SiteLocation", b =>
                {
                    b.HasOne("OptraxDAL.Models.Admin.Business", "Business")
                        .WithMany("Sites")
                        .HasForeignKey("BusinessID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Business");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.TransferEvent", b =>
                {
                    b.HasOne("OptraxDAL.Models.Inventory.InventoryTransfer", "Transfer")
                        .WithOne("PlantTransfer")
                        .HasForeignKey("OptraxDAL.Models.Grow.TransferEvent", "TransferID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.TransplantEvent", b =>
                {
                    b.HasOne("OptraxDAL.Models.Inventory.ContainerType", "NewContainer")
                        .WithMany()
                        .HasForeignKey("NewContainerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewContainer");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.TreatmentEvent", b =>
                {
                    b.HasOne("OptraxDAL.Models.Inventory.ConsumableItem", "Product")
                        .WithMany("PlantTreatments")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.ConsumableItem", b =>
                {
                    b.HasOne("OptraxDAL.Models.Inventory.StockItem", null)
                        .WithOne()
                        .HasForeignKey("OptraxDAL.Models.Inventory.ConsumableItem", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Admin.UoM", "UnitUoM")
                        .WithMany()
                        .HasForeignKey("UoMName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnitUoM");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.DurableItem", b =>
                {
                    b.HasOne("OptraxDAL.Models.Inventory.StockItem", null)
                        .WithOne()
                        .HasForeignKey("OptraxDAL.Models.Inventory.DurableItem", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.Light", b =>
                {
                    b.HasOne("OptraxDAL.Models.Inventory.StockItem", null)
                        .WithOne()
                        .HasForeignKey("OptraxDAL.Models.Inventory.Light", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.Plant", b =>
                {
                    b.HasOne("OptraxDAL.Models.Grow.Crop", "Crop")
                        .WithMany("Plants")
                        .HasForeignKey("CropID");

                    b.HasOne("OptraxDAL.Models.Inventory.StockItem", null)
                        .WithOne()
                        .HasForeignKey("OptraxDAL.Models.Inventory.Plant", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Inventory.Plant", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentID");

                    b.HasOne("OptraxDAL.Models.Grow.Strain", "Strain")
                        .WithMany()
                        .HasForeignKey("StrainID");

                    b.Navigation("Crop");

                    b.Navigation("Parent");

                    b.Navigation("Strain");
                });

            modelBuilder.Entity("OptraxDAL.Models.Map.MapLine", b =>
                {
                    b.HasOne("OptraxDAL.Models.Map.MapObject", null)
                        .WithOne()
                        .HasForeignKey("OptraxDAL.Models.Map.MapLine", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptraxDAL.Models.Map.MapPoint", b =>
                {
                    b.HasOne("OptraxDAL.Models.Map.MapObject", null)
                        .WithOne()
                        .HasForeignKey("OptraxDAL.Models.Map.MapPoint", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Map.MapIcon", "Icon")
                        .WithMany("Points")
                        .HasForeignKey("IconID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Admin.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID");

                    b.HasOne("OptraxDAL.Models.Map.MapLine", null)
                        .WithMany("Points")
                        .HasForeignKey("MapLineID");

                    b.HasOne("OptraxDAL.Models.Map.MapPolygon", null)
                        .WithMany("Points")
                        .HasForeignKey("MapPolygonID");

                    b.Navigation("Icon");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("OptraxDAL.Models.Map.MapPolygon", b =>
                {
                    b.HasOne("OptraxDAL.Models.Map.MapObject", null)
                        .WithOne()
                        .HasForeignKey("OptraxDAL.Models.Map.MapPolygon", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Admin.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.Address", b =>
                {
                    b.Navigation("Building");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.AppUser", b =>
                {
                    b.Navigation("InventoryTransfers");

                    b.Navigation("PlantEvents");

                    b.Navigation("TransferApprovals");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.Business", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Buildings");

                    b.Navigation("Sites");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.Location", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("TransfersIn");

                    b.Navigation("TransfersOut");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Crop", b =>
                {
                    b.Navigation("Plants");

                    b.Navigation("ProductItems");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Strain", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Crops");

                    b.Navigation("Parents");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.ContainerType", b =>
                {
                    b.Navigation("Transplants");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.InventoryCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.InventoryItem", b =>
                {
                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.InventoryTransfer", b =>
                {
                    b.Navigation("Approval");

                    b.Navigation("PlantTransfer");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.StockItem", b =>
                {
                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("OptraxDAL.Models.Map.IconCollection", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("OptraxDAL.Models.Map.MapIcon", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("OptraxDAL.Models.Products.Product", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("OptraxDAL.Models.Products.ProductBatch", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.FieldLocation", b =>
                {
                    b.Navigation("Crops");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.GreenhouseLocation", b =>
                {
                    b.Navigation("Crops");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.RoomLocation", b =>
                {
                    b.Navigation("Crops");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.RowLocation", b =>
                {
                    b.Navigation("Crops");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.ConsumableItem", b =>
                {
                    b.Navigation("PlantTreatments");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.Light", b =>
                {
                    b.Navigation("PlantLightEvents");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.Plant", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("PlantEvents");
                });

            modelBuilder.Entity("OptraxDAL.Models.Map.MapLine", b =>
                {
                    b.Navigation("Points");
                });

            modelBuilder.Entity("OptraxDAL.Models.Map.MapPolygon", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
