// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OptraxDAL;

#nullable disable

namespace OptraxDAL.Migrations
{
    [DbContext(typeof(OptraxContext))]
    [Migration("20250216175453_InventoryCategoryModelUpdate2")]
    partial class InventoryCategoryModelUpdate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "Identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "Identity");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BuildingID")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompannyID")
                        .HasColumnType("int");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", "Identity");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.Building", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AddressID")
                        .IsUnique();

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AddressID")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.ContainerType", b =>
                {
                    b.Property<int>("ContainerTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContainerTypeID"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Capacity")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("CapacityUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InventoryItemID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContainerTypeID");

                    b.HasIndex("InventoryItemID");

                    b.ToTable("ContainerTypes");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Crop", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ActualFlowerDays")
                        .HasColumnType("int");

                    b.Property<int?>("ActualVegDays")
                        .HasColumnType("int");

                    b.Property<int?>("BatchID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ExpectedFlowerDays")
                        .HasColumnType("int");

                    b.Property<int?>("ExpectedVegDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProductQuantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ProductQuantityUOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StrainID")
                        .HasColumnType("int");

                    b.Property<decimal?>("WasteQuantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("WasteQuantityUOM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RoomID");

                    b.HasIndex("StrainID");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Light", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("BulbType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorSpectrum")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("CoverageAreaSF")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("InventoryStockID")
                        .HasColumnType("int");

                    b.Property<int?>("InventoryStockItemID")
                        .HasColumnType("int");

                    b.Property<int?>("LifespanHours")
                        .HasColumnType("int");

                    b.Property<decimal?>("PPF")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("PPFD")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("RoomID")
                        .HasColumnType("int");

                    b.Property<int?>("Voltage")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("InventoryStockItemID");

                    b.HasIndex("RoomID");

                    b.ToTable("Lights");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Plant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ContainerID")
                        .HasColumnType("int");

                    b.Property<int?>("CropID")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentContainerContainerTypeID")
                        .HasColumnType("int");

                    b.Property<string>("GrowthPhase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InventoryStockItemID")
                        .HasColumnType("int");

                    b.Property<bool>("IsMother")
                        .HasColumnType("bit");

                    b.Property<int?>("LightID")
                        .HasColumnType("int");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.Property<int?>("RoomID")
                        .HasColumnType("int");

                    b.Property<string>("StartType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StrainID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CropID");

                    b.HasIndex("CurrentContainerContainerTypeID");

                    b.HasIndex("InventoryStockItemID");

                    b.HasIndex("LightID");

                    b.HasIndex("ParentID");

                    b.HasIndex("RoomID");

                    b.HasIndex("StrainID");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.PlantAction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ActionSubType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantID")
                        .HasColumnType("int");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PlantID");

                    b.ToTable("PlantActions");

                    b.HasDiscriminator<string>("TransferType").HasValue("PlantAction");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.PlantTransfer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ActionID")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DestinationID")
                        .HasColumnType("int")
                        .HasColumnName("DestinationID");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginID")
                        .HasColumnType("int")
                        .HasColumnName("OriginID");

                    b.Property<int>("PlantID")
                        .HasColumnType("int");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PlantID");

                    b.ToTable("PlantTransfers");

                    b.HasDiscriminator<string>("TransferType").HasValue("PlantTransfer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Strain", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneticOrigin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OriginCompanyID")
                        .HasColumnType("int");

                    b.Property<string>("StrainType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Strains");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.StrainRelationship", b =>
                {
                    b.Property<int>("ParentID")
                        .HasColumnType("int");

                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.HasKey("ParentID", "ChildID");

                    b.HasIndex("ChildID");

                    b.ToTable("StrainRelationships");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.InventoryCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.ToTable("InventoryCategories");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.InventoryItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("DefaultUOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LightID")
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlantID")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StockCount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("StockUOM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("LightID");

                    b.HasIndex("PlantID");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.InventoryLocation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("InventoryLocation");

                    b.HasDiscriminator<string>("LocationType").HasValue("InventoryLocation");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.InventoryStockItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTimeOffset?>("ExpirationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("InventoryItemID")
                        .HasColumnType("int");

                    b.Property<int?>("LocationID")
                        .HasColumnType("int");

                    b.Property<string>("LotNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("PurchaseDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UOM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("InventoryItemID");

                    b.HasIndex("LocationID");

                    b.ToTable("InventoryStockItems");
                });

            modelBuilder.Entity("OptraxDAL.Models.Products.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductUnitUOM")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OptraxDAL.Models.Products.ProductBatch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BatchNumber")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("UnitQuantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductBatches");
                });

            modelBuilder.Entity("OptraxDAL.Models.Products.ProductItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BatchID")
                        .HasColumnType("int");

                    b.Property<int?>("CropID")
                        .HasColumnType("int");

                    b.Property<int?>("InventoryLocationID")
                        .HasColumnType("int");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasFilter("[Barcode] IS NOT NULL");

                    b.HasIndex("BatchID");

                    b.HasIndex("CropID");

                    b.HasIndex("InventoryLocationID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductItems");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.PruneAction", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Grow.PlantAction");

                    b.Property<string>("PruneType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("PlantActions");

                    b.HasDiscriminator().HasValue("Prune");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.TransferAction", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Grow.PlantAction");

                    b.Property<int>("TransferID")
                        .HasColumnType("int");

                    b.HasIndex("TransferID")
                        .IsUnique()
                        .HasFilter("[TransferID] IS NOT NULL");

                    b.ToTable("PlantActions");

                    b.HasDiscriminator().HasValue("Transfer");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.TreatmentAction", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Grow.PlantAction");

                    b.Property<int?>("InventoryItemID")
                        .HasColumnType("int");

                    b.Property<decimal?>("QuantityApplied")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("QuantityUOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreatmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("InventoryItemID");

                    b.ToTable("PlantActions");

                    b.HasDiscriminator().HasValue("Treatment");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.ContainerTransfer", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Grow.PlantTransfer");

                    b.HasIndex("DestinationID");

                    b.HasIndex("OriginID");

                    b.ToTable("PlantTransfers");

                    b.HasDiscriminator().HasValue("Container");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.LightTransfer", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Grow.PlantTransfer");

                    b.HasIndex("DestinationID");

                    b.HasIndex("OriginID");

                    b.ToTable("PlantTransfers");

                    b.HasDiscriminator().HasValue("Light");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.RoomTransfer", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Grow.PlantTransfer");

                    b.HasIndex("DestinationID");

                    b.HasIndex("OriginID");

                    b.ToTable("PlantTransfers");

                    b.HasDiscriminator().HasValue("Room");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.BuildingLocation", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Inventory.InventoryLocation");

                    b.Property<int>("BuildingID")
                        .HasColumnType("int");

                    b.HasIndex("BuildingID")
                        .IsUnique()
                        .HasFilter("[BuildingID] IS NOT NULL");

                    b.ToTable("InventoryLocation");

                    b.HasDiscriminator().HasValue("Building");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.ContainerLocation", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Inventory.InventoryLocation");

                    b.ToTable("InventoryLocation");

                    b.HasDiscriminator().HasValue("Container");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.OffsiteLocation", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Inventory.InventoryLocation");

                    b.ToTable("InventoryLocation");

                    b.HasDiscriminator().HasValue("Offsite");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.RoomLocation", b =>
                {
                    b.HasBaseType("OptraxDAL.Models.Inventory.InventoryLocation");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.HasIndex("RoomID")
                        .IsUnique()
                        .HasFilter("[RoomID] IS NOT NULL");

                    b.ToTable("InventoryLocation");

                    b.HasDiscriminator().HasValue("Room");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OptraxDAL.Models.Admin.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OptraxDAL.Models.Admin.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Admin.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OptraxDAL.Models.Admin.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.Building", b =>
                {
                    b.HasOne("OptraxDAL.Models.Admin.Address", "Address")
                        .WithOne("Building")
                        .HasForeignKey("OptraxDAL.Models.Admin.Building", "AddressID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.Company", b =>
                {
                    b.HasOne("OptraxDAL.Models.Admin.Address", "Address")
                        .WithOne("Company")
                        .HasForeignKey("OptraxDAL.Models.Admin.Company", "AddressID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.ContainerType", b =>
                {
                    b.HasOne("OptraxDAL.Models.Inventory.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Crop", b =>
                {
                    b.HasOne("OptraxDAL.Models.Grow.Room", "Room")
                        .WithMany("Crops")
                        .HasForeignKey("RoomID");

                    b.HasOne("OptraxDAL.Models.Grow.Strain", "Strain")
                        .WithMany()
                        .HasForeignKey("StrainID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Strain");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Light", b =>
                {
                    b.HasOne("OptraxDAL.Models.Inventory.InventoryStockItem", "InventoryStockItem")
                        .WithMany()
                        .HasForeignKey("InventoryStockItemID");

                    b.HasOne("OptraxDAL.Models.Grow.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomID");

                    b.Navigation("InventoryStockItem");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Plant", b =>
                {
                    b.HasOne("OptraxDAL.Models.Grow.Crop", "Crop")
                        .WithMany("Plants")
                        .HasForeignKey("CropID");

                    b.HasOne("OptraxDAL.Models.Grow.ContainerType", "CurrentContainer")
                        .WithMany("Plants")
                        .HasForeignKey("CurrentContainerContainerTypeID");

                    b.HasOne("OptraxDAL.Models.Inventory.InventoryStockItem", "InventoryStockItem")
                        .WithMany()
                        .HasForeignKey("InventoryStockItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Grow.Light", "CurrentLight")
                        .WithMany("Plants")
                        .HasForeignKey("LightID");

                    b.HasOne("OptraxDAL.Models.Grow.Plant", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentID");

                    b.HasOne("OptraxDAL.Models.Grow.Room", "CurrentRoom")
                        .WithMany("Plants")
                        .HasForeignKey("RoomID");

                    b.HasOne("OptraxDAL.Models.Grow.Strain", "Strain")
                        .WithMany("Plants")
                        .HasForeignKey("StrainID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("CurrentContainer");

                    b.Navigation("CurrentLight");

                    b.Navigation("CurrentRoom");

                    b.Navigation("InventoryStockItem");

                    b.Navigation("Parent");

                    b.Navigation("Strain");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.PlantAction", b =>
                {
                    b.HasOne("OptraxDAL.Models.Grow.Plant", "Plant")
                        .WithMany("Actions")
                        .HasForeignKey("PlantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.PlantTransfer", b =>
                {
                    b.HasOne("OptraxDAL.Models.Grow.Plant", "Plant")
                        .WithMany("Transfers")
                        .HasForeignKey("PlantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.StrainRelationship", b =>
                {
                    b.HasOne("OptraxDAL.Models.Grow.Strain", "ChildStrain")
                        .WithMany("Parents")
                        .HasForeignKey("ChildID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Grow.Strain", "ParentStrain")
                        .WithMany("Children")
                        .HasForeignKey("ParentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildStrain");

                    b.Navigation("ParentStrain");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.InventoryCategory", b =>
                {
                    b.HasOne("OptraxDAL.Models.Inventory.InventoryCategory", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentID");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.InventoryItem", b =>
                {
                    b.HasOne("OptraxDAL.Models.Inventory.InventoryCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Grow.Light", "Light")
                        .WithMany()
                        .HasForeignKey("LightID");

                    b.HasOne("OptraxDAL.Models.Grow.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantID");

                    b.Navigation("Category");

                    b.Navigation("Light");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.InventoryStockItem", b =>
                {
                    b.HasOne("OptraxDAL.Models.Inventory.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Inventory.InventoryLocation", "Location")
                        .WithMany("StockItems")
                        .HasForeignKey("LocationID");

                    b.Navigation("InventoryItem");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("OptraxDAL.Models.Products.ProductBatch", b =>
                {
                    b.HasOne("OptraxDAL.Models.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OptraxDAL.Models.Products.ProductItem", b =>
                {
                    b.HasOne("OptraxDAL.Models.Products.ProductBatch", "Batch")
                        .WithMany("Units")
                        .HasForeignKey("BatchID");

                    b.HasOne("OptraxDAL.Models.Grow.Crop", null)
                        .WithMany("ProductItems")
                        .HasForeignKey("CropID");

                    b.HasOne("OptraxDAL.Models.Inventory.InventoryLocation", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("InventoryLocationID");

                    b.HasOne("OptraxDAL.Models.Products.Product", "Product")
                        .WithMany("Units")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");

                    b.Navigation("CurrentLocation");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.TransferAction", b =>
                {
                    b.HasOne("OptraxDAL.Models.Grow.PlantTransfer", "Transfer")
                        .WithOne("PlantAction")
                        .HasForeignKey("OptraxDAL.Models.Grow.TransferAction", "TransferID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.TreatmentAction", b =>
                {
                    b.HasOne("OptraxDAL.Models.Inventory.InventoryStockItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemID");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.ContainerTransfer", b =>
                {
                    b.HasOne("OptraxDAL.Models.Grow.ContainerType", "ToContainer")
                        .WithMany("TransfersIn")
                        .HasForeignKey("DestinationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Grow.ContainerType", "FromContainer")
                        .WithMany("TransfersOut")
                        .HasForeignKey("OriginID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromContainer");

                    b.Navigation("ToContainer");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.LightTransfer", b =>
                {
                    b.HasOne("OptraxDAL.Models.Grow.Light", "ToLight")
                        .WithMany("TransfersIn")
                        .HasForeignKey("DestinationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Grow.Light", "FromLight")
                        .WithMany("TransfersOut")
                        .HasForeignKey("OriginID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromLight");

                    b.Navigation("ToLight");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.RoomTransfer", b =>
                {
                    b.HasOne("OptraxDAL.Models.Grow.Room", "ToRoom")
                        .WithMany("TransfersIn")
                        .HasForeignKey("DestinationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OptraxDAL.Models.Grow.Room", "FromRoom")
                        .WithMany("TransfersOut")
                        .HasForeignKey("OriginID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromRoom");

                    b.Navigation("ToRoom");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.BuildingLocation", b =>
                {
                    b.HasOne("OptraxDAL.Models.Admin.Building", "Building")
                        .WithOne("Location")
                        .HasForeignKey("OptraxDAL.Models.Inventory.BuildingLocation", "BuildingID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.RoomLocation", b =>
                {
                    b.HasOne("OptraxDAL.Models.Grow.Room", "Room")
                        .WithOne("Location")
                        .HasForeignKey("OptraxDAL.Models.Inventory.RoomLocation", "RoomID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.Address", b =>
                {
                    b.Navigation("Building");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OptraxDAL.Models.Admin.Building", b =>
                {
                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.ContainerType", b =>
                {
                    b.Navigation("Plants");

                    b.Navigation("TransfersIn");

                    b.Navigation("TransfersOut");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Crop", b =>
                {
                    b.Navigation("Plants");

                    b.Navigation("ProductItems");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Light", b =>
                {
                    b.Navigation("Plants");

                    b.Navigation("TransfersIn");

                    b.Navigation("TransfersOut");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Plant", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.PlantTransfer", b =>
                {
                    b.Navigation("PlantAction")
                        .IsRequired();
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Room", b =>
                {
                    b.Navigation("Crops");

                    b.Navigation("Location");

                    b.Navigation("Plants");

                    b.Navigation("TransfersIn");

                    b.Navigation("TransfersOut");
                });

            modelBuilder.Entity("OptraxDAL.Models.Grow.Strain", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Parents");

                    b.Navigation("Plants");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.InventoryCategory", b =>
                {
                    b.Navigation("ChildCategories");
                });

            modelBuilder.Entity("OptraxDAL.Models.Inventory.InventoryLocation", b =>
                {
                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("OptraxDAL.Models.Products.Product", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("OptraxDAL.Models.Products.ProductBatch", b =>
                {
                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
